Primera adición
MacielFede/msnPlus pull request #2
Opened 2023-06-15 00:09 UTC by castjuan

Interfaces
Algunos DTs vacíos por dependencias
Clase conversación
EL GRAN CAMBIO DE "Fabrica" a "FACTORY"

2023-06-15 00:34 UTC, MacielFede approved these changes
Que linda aplastada de teclado hizo con sus nalgas señor

2023-06-15 13:12 UTC, michaelramos95 approved these changes
Leave a comment

2023-06-15 13:21 UTC, MacielFede requested changes
Juan te falto en Conversacion.h agregar un map de Mensajes, ademas getDataConversacion tendria que ser virtual pura.

2023-06-18 17:16 UTC, MacielFede approved these changes

2023-06-18 17:16 UTC, merged